PRAGMA foreign_keys = ON;

BEGIN;

-- =========================================================
-- MAITRI EMS / POLARIS EMS
-- SQLite Database Schema
-- PostgreSQL-compatible structure converted for SQLite
-- =========================================================

-- =========================================================
-- ENUM-LIKE CHECK CONSTRAINTS
-- =========================================================

-- NOTE:
-- PostgreSQL ENUMs are represented as TEXT columns with CHECK constraints.
-- UUIDs are stored as TEXT values generated by the application.
-- TIMESTAMPTZ values are stored as ISO-8601 TEXT timestamps.
-- JSONB values are stored as TEXT containing JSON.

-- =========================================================
-- 1. STATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS stations (
    id TEXT PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,
    country TEXT DEFAULT 'India',

    latitude REAL,
    longitude REAL,
    elevation_m REAL,

    status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);


-- =========================================================
-- 2. DATA SOURCES
-- =========================================================

CREATE TABLE IF NOT EXISTS data_sources (
    id TEXT PRIMARY KEY,

    name TEXT NOT NULL,
    source_type TEXT NOT NULL CHECK (source_type IN (
        'NCPOR',
        'ERA5',
        'AUSTRALIAN_ANTARCTIC_DATA',
        'SENSOR',
        'MANUAL',
        'SIMULATION'
    )),

    description TEXT,
    url TEXT,

    update_frequency TEXT,

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);


-- =========================================================
-- 3. ASSETS
-- =========================================================

CREATE TABLE IF NOT EXISTS assets (
    id TEXT PRIMARY KEY,

    station_id TEXT NOT NULL
        REFERENCES stations(id)
        ON DELETE CASCADE,

    name TEXT NOT NULL,

    asset_type TEXT NOT NULL CHECK (asset_type IN (
        'WIND_TURBINE',
        'SOLAR_PV',
        'DIESEL_GENERATOR',
        'BATTERY',
        'HYDROGEN_STORAGE',
        'FUEL_CELL',
        'ELECTROLYZER'
    )),

    capacity_kw REAL,
    capacity_kwh REAL,

    efficiency REAL,

    status TEXT DEFAULT 'ONLINE' CHECK (status IN (
        'ONLINE',
        'OFFLINE',
        'STANDBY',
        'FAULT',
        'MAINTENANCE'
    )),

    installation_date TEXT,

    metadata TEXT DEFAULT '{}',

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    UNIQUE(station_id, name)
);


-- =========================================================
-- 4. WEATHER OBSERVATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS weather_observations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    station_id TEXT NOT NULL
        REFERENCES stations(id)
        ON DELETE CASCADE,

    source_id TEXT
        REFERENCES data_sources(id),

    observed_at TEXT NOT NULL,

    temperature_c REAL,
    humidity_percent REAL,

    pressure_hpa REAL,

    wind_speed_ms REAL,
    wind_direction_deg REAL,

    solar_irradiance_wm2 REAL,

    precipitation_mm REAL,

    cloud_cover_percent REAL,

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    UNIQUE(station_id, observed_at, source_id)
);

CREATE INDEX IF NOT EXISTS idx_weather_station_time
ON weather_observations(station_id, observed_at);


-- =========================================================
-- 5. WEATHER / ENERGY FORECASTS
-- =========================================================

CREATE TABLE IF NOT EXISTS forecasts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    station_id TEXT NOT NULL
        REFERENCES stations(id)
        ON DELETE CASCADE,

    source_id TEXT
        REFERENCES data_sources(id),

    forecast_type TEXT NOT NULL CHECK (forecast_type IN (
        'WEATHER',
        'LOAD',
        'WIND',
        'SOLAR',
        'ENERGY'
    )),

    model_name TEXT,

    generated_at TEXT NOT NULL,

    valid_from TEXT NOT NULL,
    valid_until TEXT NOT NULL,

    predicted_value REAL,

    unit TEXT,

    confidence REAL,

    metadata TEXT DEFAULT '{}',

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_forecasts_station_time
ON forecasts(station_id, valid_from);


-- =========================================================
-- 6. ENERGY READINGS
-- =========================================================

CREATE TABLE IF NOT EXISTS energy_readings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    station_id TEXT NOT NULL
        REFERENCES stations(id)
        ON DELETE CASCADE,

    asset_id TEXT
        REFERENCES assets(id)
        ON DELETE SET NULL,

    recorded_at TEXT NOT NULL,

    power_kw REAL,

    energy_kwh REAL,

    voltage_v REAL,
    current_a REAL,

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_energy_station_time
ON energy_readings(station_id, recorded_at);

CREATE INDEX IF NOT EXISTS idx_energy_asset_time
ON energy_readings(asset_id, recorded_at);


-- =========================================================
-- 7. BATTERY READINGS
-- =========================================================

CREATE TABLE IF NOT EXISTS battery_readings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    asset_id TEXT NOT NULL
        REFERENCES assets(id)
        ON DELETE CASCADE,

    recorded_at TEXT NOT NULL,

    soc_percent REAL,

    soh_percent REAL,

    power_kw REAL,

    voltage_v REAL,

    current_a REAL,

    temperature_c REAL,

    cycle_count INTEGER,

    charge_limit_kw REAL,

    discharge_limit_kw REAL,

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_battery_asset_time
ON battery_readings(asset_id, recorded_at);


-- =========================================================
-- 8. FUEL / DIESEL READINGS
-- =========================================================

CREATE TABLE IF NOT EXISTS fuel_readings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    asset_id TEXT NOT NULL
        REFERENCES assets(id)
        ON DELETE CASCADE,

    recorded_at TEXT NOT NULL,

    fuel_level_liters REAL,

    consumption_lph REAL,

    generator_power_kw REAL,

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_fuel_asset_time
ON fuel_readings(asset_id, recorded_at);


-- =========================================================
-- 9. DISPATCH PLANS
-- =========================================================

CREATE TABLE IF NOT EXISTS dispatch_plans (
    id TEXT PRIMARY KEY,

    station_id TEXT NOT NULL
        REFERENCES stations(id)
        ON DELETE CASCADE,

    plan_date TEXT NOT NULL,

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    status TEXT DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED')),

    optimization_model TEXT,

    total_fuel_liters REAL,

    total_co2_kg REAL,

    reliability_score REAL,

    notes TEXT
);


-- =========================================================
-- 10. DISPATCH ITEMS
-- =========================================================

CREATE TABLE IF NOT EXISTS dispatch_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    dispatch_plan_id TEXT NOT NULL
        REFERENCES dispatch_plans(id)
        ON DELETE CASCADE,

    asset_id TEXT
        REFERENCES assets(id)
        ON DELETE SET NULL,

    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,

    planned_power_kw REAL,

    planned_energy_kwh REAL,

    fuel_consumption_liters REAL,

    co2_kg REAL,

    battery_soc_target REAL,

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_dispatch_plan_time
ON dispatch_items(dispatch_plan_id, start_time);


-- =========================================================
-- 11. ALERTS
-- =========================================================

CREATE TABLE IF NOT EXISTS alerts (
    id TEXT PRIMARY KEY,

    station_id TEXT NOT NULL
        REFERENCES stations(id)
        ON DELETE CASCADE,

    asset_id TEXT
        REFERENCES assets(id)
        ON DELETE SET NULL,

    source_id TEXT
        REFERENCES data_sources(id),

    title TEXT NOT NULL,

    severity TEXT NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),

    status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED')),

    description TEXT,

    triggered_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    acknowledged_at TEXT,

    resolved_at TEXT,

    metadata TEXT DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_alerts_station_status
ON alerts(station_id, status);

CREATE INDEX IF NOT EXISTS idx_alerts_triggered
ON alerts(triggered_at);


-- =========================================================
-- 12. DIGITAL TWIN SIMULATION RUNS
-- =========================================================

CREATE TABLE IF NOT EXISTS simulation_runs (
    id TEXT PRIMARY KEY,

    station_id TEXT NOT NULL
        REFERENCES stations(id)
        ON DELETE CASCADE,

    scenario_name TEXT NOT NULL,

    scenario_type TEXT,

    status TEXT DEFAULT 'RUNNING' CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),

    started_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    completed_at TEXT,

    duration_ms INTEGER,

    parameters TEXT DEFAULT '{}',

    created_by TEXT
);


-- =========================================================
-- 13. DIGITAL TWIN SIMULATION RESULTS
-- =========================================================

CREATE TABLE IF NOT EXISTS simulation_results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    simulation_id TEXT NOT NULL
        REFERENCES simulation_runs(id)
        ON DELETE CASCADE,

    metric_name TEXT NOT NULL,

    baseline_value REAL,

    simulated_value REAL,

    difference_value REAL,

    percentage_change REAL,

    unit TEXT,

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_simulation_results
ON simulation_results(simulation_id);


-- =========================================================
-- 14. REPORTS
-- =========================================================

CREATE TABLE IF NOT EXISTS reports (
    id TEXT PRIMARY KEY,

    station_id TEXT NOT NULL
        REFERENCES stations(id)
        ON DELETE CASCADE,

    report_type TEXT NOT NULL,

    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,

    generated_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    file_format TEXT,

    file_path TEXT,

    metadata TEXT DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_reports_station_period
ON reports(station_id, period_start, period_end);


-- =========================================================
-- 15. USERS
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,

    name TEXT NOT NULL,

    email TEXT UNIQUE NOT NULL,

    password_hash TEXT,

    role TEXT DEFAULT 'OPERATOR',

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);


-- =========================================================
-- 16. AUDIT LOG
-- =========================================================

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    user_id TEXT
        REFERENCES users(id)
        ON DELETE SET NULL,

    action TEXT NOT NULL,

    entity_type TEXT,

    entity_id TEXT,

    details TEXT DEFAULT '{}',

    created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_time
ON audit_logs(created_at);

COMMIT;
