import { Bar, BarChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import Panel from '../common/Panel.jsx';

export function DispatchPlanChart({ data }) {
  return <Panel eyebrow="ROLLING HORIZON DISPATCH PLAN - 24HR" className="dispatch-plan-panel" action={<div className="dispatch-legend"><span className="dispatch-legend-wind">■ Wind</span><span className="dispatch-legend-solar">■ Solar</span><span className="dispatch-legend-diesel">■ Diesel</span><span className="dispatch-legend-battery">■ Battery +/-</span></div>}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} barCategoryGap="19%" margin={{ top: 12, right: 8, bottom: 0, left: 0 }}><CartesianGrid stroke="#153452" vertical={false} /><XAxis dataKey="hour" interval={3} tick={{ fill: '#37668f', fontSize: 10 }} tickLine={false} axisLine={false} /><YAxis domain={[0, 160]} ticks={[0, 40, 80, 120, 160]} tick={{ fill: '#37668f', fontSize: 10 }} tickLine={false} axisLine={false} width={34} /><Tooltip cursor={{ fill: '#102a45' }} contentStyle={{ background: '#0b2946', border: '1px solid #24547b', color: '#a1d9ff', fontSize: 11 }} /><Bar dataKey="wind" stackId="dispatch" fill="#00d0a1" /><Bar dataKey="solar" stackId="dispatch" fill="#ffbd16" /><Bar dataKey="diesel" stackId="dispatch" fill="#ff6633" /><Bar dataKey="battery" stackId="dispatch" fill="#4db8ff" /></BarChart></ResponsiveContainer></Panel>;
}

export function BatteryScheduleChart({ data }) {
  return <Panel eyebrow="BATTERY CHARGE / DISCHARGE SCHEDULE" className="battery-schedule-panel"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}><CartesianGrid stroke="#153452" vertical={false} /><XAxis dataKey="hour" interval={5} tick={{ fill: '#37668f', fontSize: 10 }} tickLine={false} axisLine={false} /><YAxis domain={[-20, 20]} ticks={[-20, -10, 0, 10, 20]} tick={{ fill: '#37668f', fontSize: 10 }} tickLine={false} axisLine={false} width={30} /><ReferenceLine y={0} stroke="#5790b7" /><Tooltip cursor={{ fill: '#102a45' }} contentStyle={{ background: '#0b2946', border: '1px solid #24547b', color: '#a1d9ff', fontSize: 11 }} /><Bar dataKey="value" fill="#4db8ff" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></Panel>;
}
